/**
 * Copyright (C) 2020, ControlThings Oy Ab
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @license Apache-2.0
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_ct_wish_bridge_WishCoreJni */

#ifndef _Included_fi_ct_wish_bridge_WishCoreJni
#define _Included_fi_ct_wish_bridge_WishCoreJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_ct_wish_bridge_WishCoreJni
 * Method:    register_core_bridge
 * Signature: (Lfi/ct/wish/bridge/WishCoreBridge;)V
 */
JNIEXPORT void JNICALL Java_fi_ct_wish_bridge_WishCoreJni_register_1core_1bridge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fi_ct_wish_bridge_WishCoreJni
 * Method:    jni_receive_app_to_core
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_wish_bridge_WishCoreJni_jni_1receive_1app_1to_1core
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     fi_ct_wish_bridge_WishCoreJni
 * Method:    remove_service
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_fi_ct_wish_bridge_WishCoreJni_remove_1service
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
